export default {
  index: {
    iconIndex: require('../images/index/dt.png'),
    iconIndexSelected: require('../images/index/dt-s.png'),
    iconResult: require('../images/index/bf.png'),
    iconResultSelected: require('../images/index/bf-s.png'),
    iconCopy: require('../images/index/scopy.png'),
    iconLottery: require('../images/index/kj.png'),
    iconLotterySelected: require('../images/index/kj-s.png'),
    iconPersonal: require('../images/index/grzx.png'),
    iconPersonalSelected: require('../images/index/grzx-s.png'),
    download:require('../images/index/app-download.png'),
  },
  personal:{
    unLogin:require('../images/personal/unlogin.png'),
    myOrder:require('../images/personal/setting.png'),
    connect:require('../images/personal/gl-dz.png'),
    switchRole:require('../images/personal/changerole.png'),
    booking:require('../images/personal/follow.png'),
    activity:require('../images/personal/redsquare.png'),
    security:require('../images/personal/update.png'),
    inviteCode:require('../images/personal/invite-code.png'),
    feedback:require('../images/personal/webs.png'),
    setting:require('../images/personal/setting.png'),
    score:require('../images/personal/jfgl.png'),
  },
  customService:require('../images/kf-home.png'),
  cellphone:require('../images/tel.png'),
  message:require('../images/message.png'),
};
